INSERT INTO ACCOUNT 
SELECT * FROM csvread('data_account.csv');

INSERT INTO BRANCH 
SELECT * FROM csvread('data_branch.csv');

INSERT INTO TRANSACTION(TRANSACTION_DATE ,ACCOUNT_NO, TRANSACTION_NO ,TRANSACTION_AMOUNT,TRANSACTION_FEE, CANCLE_YN)
SELECT * FROM csvread('data_transaction.csv');