server:
   port: 80
   
# H2 설정
spring:
   h2:
      console:
         enabled: true
         path : /h2

# Datasource 설정
   datasource:
      platform: h2
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:test
      username: sa
      password:
      
   jpa:
      database: h2
      hibernate: 
         dialect: org.hibernate.dialect.H2Dialect
         ddl-auto: create-drop
      generate-ddl: true

   http:
      encoding:
         charset: UTF-8
         enabled: true
         force: true